plugins {
    id 'application'
}

group = 'ru.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(11)
    }
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.11.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    testImplementation 'org.seleniumhq.selenium:selenium-java:4.29.0'
}

test {
    useJUnitPlatform()
}

application {
    mainClass = 'ru.example.App'
}